/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciamentopizzaria;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago
 */
public class TelaPrincipal extends javax.swing.JFrame {

    int idCliente = 0;
    int idProduto = 0;
    int idPedido = 0;
    
    File arquivo;
    
    DefaultListModel dmCliente = new DefaultListModel();
    DefaultListModel dmProduto = new DefaultListModel();
    DefaultListModel dmPedido = new DefaultListModel();
    DefaultListModel dmAdicionaProduto1 = new DefaultListModel();
    DefaultListModel dmAdicionaProduto2 = new DefaultListModel();
    
    ArrayList<Cliente> listaClientes = new ArrayList();  
    ArrayList<Produto> listaProdutos = new ArrayList(); 
    ArrayList<Pedido> listaPedidos = new ArrayList();
    ArrayList<ProdutoPedido> listaProdutoPedido = new ArrayList();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
                
        listaOsProdutos();
        listaOsProdutosAdicionaPedidos1();
        listaOsProdutosAdicionaPedidos2();
        listaOsPedidos();
        listaOsClientes();
        listaOsClientesNoCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAdicionaPedidos1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAdicionaPedidos2 = new javax.swing.JList();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonRetirar = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jButtonAdicionaPedido = new javax.swing.JButton();
        jComboBoxAdicionarPedidos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListPedidos = new javax.swing.JList();
        jButtonRemoverPedido = new javax.swing.JButton();
        jButtonLimparPedidos = new javax.swing.JButton();
        jButtonGerarCsv = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCliente = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jTextFieldTelefoneCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonAdicionarCliente = new javax.swing.JButton();
        jButtonAtualizarCliente = new javax.swing.JButton();
        jButtonRemoverCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListProdutos = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldPrecoProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonAdicionarProduto = new javax.swing.JButton();
        jButtonAtualizarProduto = new javax.swing.JButton();
        jButtonRemoverProduto = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCarregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonEscolheArquivo = new javax.swing.JButton();
        jLabelNomeArquivo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de pizzaria");

        jScrollPane1.setViewportView(jListAdicionaPedidos1);

        jScrollPane2.setViewportView(jListAdicionaPedidos2);

        jButtonAdicionar.setText("Adicionar >");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonRetirar.setText("< Retirar");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTotal.setText("Total: R$ 0.00");

        jButtonAdicionaPedido.setText("Adicionar pedido");
        jButtonAdicionaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionaPedidoActionPerformed(evt);
            }
        });

        jComboBoxAdicionarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdicionarPedidosActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Lista de produtos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Pedido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxAdicionarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(111, 111, 111))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButtonAdicionaPedido)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addGap(173, 173, 173)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButtonAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRetirar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxAdicionarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAdicionaPedido)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Adicionar Pedidos", jPanel1);

        jScrollPane6.setViewportView(jListPedidos);

        jButtonRemoverPedido.setText("Remover Pedido");
        jButtonRemoverPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPedidoActionPerformed(evt);
            }
        });

        jButtonLimparPedidos.setText("Limpar Lista");
        jButtonLimparPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparPedidosActionPerformed(evt);
            }
        });

        jButtonGerarCsv.setText("Gerar CSV");
        jButtonGerarCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarCsvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonLimparPedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(jButtonRemoverPedido)
                        .addGap(212, 212, 212)
                        .addComponent(jButtonGerarCsv))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRemoverPedido)
                    .addComponent(jButtonLimparPedidos)
                    .addComponent(jButtonGerarCsv))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedidos", jPanel2);

        jListCliente.setToolTipText("");
        jListCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClienteMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListCliente);

        jLabel1.setText("Nome:");

        jTextFieldEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Endereço:");

        jLabel3.setText("Telefone:");

        jButtonAdicionarCliente.setText("Adicionar");
        jButtonAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarClienteActionPerformed(evt);
            }
        });

        jButtonAtualizarCliente.setText("Atualizar");
        jButtonAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarClienteActionPerformed(evt);
            }
        });

        jButtonRemoverCliente.setText("Remover");
        jButtonRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldTelefoneCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomeCliente)
                            .addComponent(jTextFieldEnderecoCliente)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButtonAdicionarCliente)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonAtualizarCliente)
                        .addGap(50, 50, 50)
                        .addComponent(jButtonRemoverCliente)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdicionarCliente)
                            .addComponent(jButtonAtualizarCliente)
                            .addComponent(jButtonRemoverCliente))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        jListProdutos.setToolTipText("");
        jListProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProdutosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jListProdutos);

        jLabel5.setText("Nome:");

        jTextFieldPrecoProduto.setText("0");

        jLabel6.setText("Preço");

        jButtonAdicionarProduto.setText("Adicionar");
        jButtonAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarProdutoActionPerformed(evt);
            }
        });

        jButtonAtualizarProduto.setText("Atualizar");
        jButtonAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarProdutoActionPerformed(evt);
            }
        });

        jButtonRemoverProduto.setText("Remover");
        jButtonRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeProduto)
                            .addComponent(jTextFieldPrecoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButtonAdicionarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAtualizarProduto)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverProduto)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdicionarProduto)
                            .addComponent(jButtonAtualizarProduto)
                            .addComponent(jButtonRemoverProduto))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", jPanel4);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCarregar.setText("CARREGAR");
        jButtonCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Salve apenas se sua última alteração for uma remoção.");
        jLabel9.setFocusable(false);

        jButtonEscolheArquivo.setText("Escolher arquivo");
        jButtonEscolheArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscolheArquivoActionPerformed(evt);
            }
        });

        jLabelNomeArquivo.setText("Nome do arquivo");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Caso o arquivo não for escolhido o programa escolherá \"data.dat\" por padrão");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonCarregar)
                        .addGap(157, 157, 157)
                        .addComponent(jButtonEscolheArquivo)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelNomeArquivo)
                        .addGap(99, 99, 99))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel10)
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jButtonSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCarregar)
                    .addComponent(jButtonEscolheArquivo))
                .addGap(18, 18, 18)
                .addComponent(jLabelNomeArquivo)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Configuração", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void carregaEstado(){
    
        try{
            FileInputStream arquivoLeitura;
            String caminho = jLabelNomeArquivo.getText().toString();
            if(caminho.equals("Nome do arquivo")){
                arquivoLeitura = new FileInputStream("data.dat");
            }else{
                arquivoLeitura = new FileInputStream(caminho);
            }
            
            ObjectInputStream objLeitura = new ObjectInputStream(arquivoLeitura);
            listaClientes = (ArrayList<Cliente>)objLeitura.readObject();
            listaPedidos = (ArrayList<Pedido>)objLeitura.readObject();
            listaProdutoPedido = (ArrayList<ProdutoPedido>)objLeitura.readObject();
            listaProdutos = (ArrayList<Produto>)objLeitura.readObject();
            idCliente = (int)objLeitura.readObject();
            idPedido = (int)objLeitura.readObject();
            idProduto = (int)objLeitura.readObject();
            
            objLeitura.close();
            arquivoLeitura.close();
            
            listaOsProdutosAdicionaPedidos1();
            listaOsProdutosAdicionaPedidos2();
            listaOsPedidos();
            listaOsClientes();
            listaOsProdutos();
            listaOsClientesNoCliente();
            
        }catch(Exception e1){
            
        }
    }
    
    
    private void listaOsClientes(){

       jComboBoxAdicionarPedidos.removeAllItems();
       jComboBoxAdicionarPedidos.addItem("<Selecione o Cliente>");
       
        int n = listaClientes.size();
        int i;
        for (i=0; i<n; i++) {
            
            jComboBoxAdicionarPedidos.addItem(listaClientes.get(i));
        }
    }
    
    private void listaOsProdutosAdicionaPedidos1(){

        jListAdicionaPedidos1.setModel(dmAdicionaProduto1);
        dmAdicionaProduto1.removeAllElements();
       
        int n = listaProdutos.size();
        int i;
        for (i=0; i<n; i++) {
            
            dmAdicionaProduto1.addElement(listaProdutos.get(i));
        }
    }
    
    private void listaOsProdutosAdicionaPedidos2(){

        jListAdicionaPedidos2.setModel(dmAdicionaProduto2);
        dmAdicionaProduto2.removeAllElements();
       
        int n = listaProdutoPedido.size();
        int i;
        for (i=0; i<n; i++) {
            
            dmAdicionaProduto2.addElement(listaProdutoPedido.get(i));
        }
    }
    
    void listaOsClientesNoCliente(){
        
        jListCliente.setModel(dmCliente);
        dmCliente.removeAllElements();
       
        int n = listaClientes.size();
        int i;
        for (i=0; i<n; i++) {
            
            dmCliente.addElement(listaClientes.get(i));
        }
        
    }
    void listaOsProdutos(){
    
        jListProdutos.setModel(dmProduto);
        dmProduto.removeAllElements();
       
        int n = listaProdutos.size();
        int i;
        for (i=0; i<n; i++) {
            
            dmProduto.addElement(listaProdutos.get(i));
        }
    }
    
    private void jButtonAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarClienteActionPerformed
        
        String nome = jTextFieldNomeCliente.getText();
        String end = jTextFieldEnderecoCliente.getText();
        String tel = jTextFieldTelefoneCliente.getText();
        
        if(nome.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Digite o nome do cliente");
            return;
        }
        
        Cliente cliente = new Cliente(idCliente,nome, end, tel);
        listaClientes.add(cliente);
        idCliente++;
        
        System.out.printf("idCliente: %d\n",idCliente);
        listaOsClientesNoCliente();
        listaOsClientes();
        salvaEstado();
    }//GEN-LAST:event_jButtonAdicionarClienteActionPerformed

    private void jListClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClienteMouseClicked
        
        Object selecionado = jListCliente.getSelectedValue();
        String nome = ((Cliente) selecionado).getNome();
        String end = ((Cliente) selecionado).getEndereco();
        String tel = ((Cliente) selecionado).getTelefone();
        
        jTextFieldNomeCliente.setText(nome);
        jTextFieldEnderecoCliente.setText(end);
        jTextFieldTelefoneCliente.setText(tel);
    }//GEN-LAST:event_jListClienteMouseClicked

    private void jButtonAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarClienteActionPerformed
        
        int index = jListCliente.getSelectedIndex();
        
        Object selecionado = jListCliente.getSelectedValue();
        
        if(selecionado!= null){
            String nome = jTextFieldNomeCliente.getText();
            String end = jTextFieldEnderecoCliente.getText();
            String tel = jTextFieldTelefoneCliente.getText();

            ((Cliente) selecionado).setNome(nome);
            ((Cliente) selecionado).setEndereco(end);
            ((Cliente) selecionado).setTelefone(tel);

            listaOsClientesNoCliente();
            listaOsClientes();
        }        
    }//GEN-LAST:event_jButtonAtualizarClienteActionPerformed

    void removeCliente(int id){
        int n = listaClientes.size();
        int i;
        for (i=0; i<n; i++) {
          if(listaClientes.get(i).getId() == id){
              listaClientes.remove(i);
              return;
          }
        }
    }
    
    private void jButtonRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverClienteActionPerformed
        
        Object selecionado = jListCliente.getSelectedValue();
        
        if(selecionado!= null){
            int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja remover esse cliente?","Aviso",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                int id = ((Cliente) selecionado).getId();
                removeCliente(id);
                listaOsClientes();
                listaOsClientesNoCliente();
            }            
        }  
    }//GEN-LAST:event_jButtonRemoverClienteActionPerformed

    private void jListProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProdutosMouseClicked
        
        Object selecionado = jListProdutos.getSelectedValue();
        String nome = ((Produto) selecionado).getNome();
        float preco = ((Produto) selecionado).getPreco();
        
        jTextFieldNomeProduto.setText(nome);
        jTextFieldPrecoProduto.setText(String.valueOf(preco));
    }//GEN-LAST:event_jListProdutosMouseClicked

    private void jButtonAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarProdutoActionPerformed
        
        String nome = jTextFieldNomeProduto.getText();
        String preco = jTextFieldPrecoProduto.getText();
        float precoFloat;
        
        if(nome.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Digite o nome do produto");
            return;
        }
            
        try{
            precoFloat = Float.parseFloat(preco);
        }catch(Exception e5){
            JOptionPane.showMessageDialog(null, "Preço com formato errado (use ponto)");
            return;
        }
                
        Produto produto = new Produto(idProduto,nome,precoFloat);
        listaProdutos.add(produto);
        idProduto++;
        
        jListProdutos.setModel(dmProduto);
        dmProduto.addElement(produto);
        listaOsProdutosAdicionaPedidos1();
        
        System.out.printf("idProduto: %d\n",idProduto);
        salvaEstado();
    }//GEN-LAST:event_jButtonAdicionarProdutoActionPerformed

    private void jButtonAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarProdutoActionPerformed
        
        int index = jListProdutos.getSelectedIndex();
        
        Object selecionado = jListProdutos.getSelectedValue();
        
        if(selecionado!= null){
            String nome = jTextFieldNomeProduto.getText();
            String preco = jTextFieldPrecoProduto.getText();

            ((Produto) selecionado).setNome(nome);
            ((Produto) selecionado).setPreco(Float.parseFloat(preco));

            dmProduto.setElementAt(selecionado, index);
            listaOsProdutosAdicionaPedidos1();
        } 
    }//GEN-LAST:event_jButtonAtualizarProdutoActionPerformed

    void removeProduto(int id){
        int n = listaProdutos.size();
        System.out.printf("teste: %d\n",n);
        int i;
        for (i=0; i<n; i++) {
          if(listaProdutos.get(i).getId() == id){
              System.out.printf("teste2: %d\n",i);
              listaProdutos.remove(i);
              return;
          }
        }
    }
        
    private void jButtonRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverProdutoActionPerformed
        
        Object selecionado = jListProdutos.getSelectedValue();
        
        if(selecionado!= null){
            int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja remover esse produto?","Aviso",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                int id = ((Produto) selecionado).getId();
                removeProduto(id);
                listaOsProdutos();
                listaOsProdutosAdicionaPedidos1();
            }
        }  
    }//GEN-LAST:event_jButtonRemoverProdutoActionPerformed

    ProdutoPedido adicionaProduto(Produto produto){
        ProdutoPedido pp;
        int n = listaProdutoPedido.size();
        int i;
        for (i=0; i<n; i++) {
            if(listaProdutoPedido.get(i).getProduto().getId() == produto.getId()){
                pp = listaProdutoPedido.get(i);
                pp.incQtd();
                return pp;
            }
        }
        pp = new ProdutoPedido(produto,1);
        listaProdutoPedido.add(pp);
        return pp;
    }
    
    void retiraProduto(int idProduto){
        ProdutoPedido pp;
        int n = listaProdutoPedido.size();
        int i;
        for (i=0; i<n; i++) {
            if(listaProdutoPedido.get(i).getProduto().getId() == idProduto){
                pp = listaProdutoPedido.get(i);
                pp.decQtd();
                if(pp.getQtd() == 0){
                    listaProdutoPedido.remove(i);
                }
                return;
            }
        }
        
    }
    
    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        
        int index = jListAdicionaPedidos1.getSelectedIndex();
        Object selecionado = jListAdicionaPedidos1.getSelectedValue();
        
        if(selecionado!= null){
            int id = ((Produto) selecionado).getId();
            String nome = ((Produto) selecionado).getNome();
            float preco = ((Produto) selecionado).getPreco();
            
            Produto novoProduto = new Produto(id,nome,preco);
            
            ProdutoPedido produtoPedido = adicionaProduto(novoProduto);
            
            if(produtoPedido.getQtd() == 1){
                jListAdicionaPedidos2.setModel(dmAdicionaProduto2);
                dmAdicionaProduto2.addElement(produtoPedido);            
            }
            listaOsProdutosAdicionaPedidos2();
            String total = Float.toString(calculaValorTotal());
            jLabelTotal.setText("Total: R$ "+total); 
        }  
        
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        
        int index = jListAdicionaPedidos1.getSelectedIndex();
        Object selecionado = jListAdicionaPedidos1.getSelectedValue();
        
        if(selecionado!= null){
            int id = ((Produto) selecionado).getId();
   
            retiraProduto(id);
            
            listaOsProdutosAdicionaPedidos2();
            String total = Float.toString(calculaValorTotal());
            jLabelTotal.setText("Total: R$ "+total); 
        }  
    }//GEN-LAST:event_jButtonRetirarActionPerformed

    float calculaValorTotal(){
    
        float total = 0;
        ProdutoPedido pp;
        int n = listaProdutoPedido.size();
        int i;
        for (i=0; i<n; i++) {
            pp = listaProdutoPedido.get(i);
            total += pp.getQtd() * pp.getProduto().getPreco();
        }
        return total;    
    }
    
    void copiaListas(ArrayList lista){
        
        ProdutoPedido pp;
        int n = listaProdutoPedido.size();
        int i;
        for (i=0; i<n; i++) {
            pp = listaProdutoPedido.get(i);
            lista.add(pp);
        }
    }
    
    void listaOsPedidos(){
    
        jListPedidos.setModel(dmPedido);
        dmPedido.removeAllElements();
       
        int n = listaPedidos.size();
        int i;
        for (i=0; i<n; i++) {
            
            dmPedido.addElement(listaPedidos.get(i));
        }
    }
    
    private void jButtonAdicionaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionaPedidoActionPerformed
        
        Pedido pedido = new Pedido();
                
        if(jComboBoxAdicionarPedidos.getSelectedItem().equals("<Selecione o Cliente>")){
            JOptionPane.showMessageDialog(null, "Escolha um cliente");
            return;
        }
        Object selecionado = jComboBoxAdicionarPedidos.getSelectedItem();
        int id = ((Cliente) selecionado).getId();
        String nome = ((Cliente) selecionado).getNome();
        String end = ((Cliente) selecionado).getEndereco();
        String tel = ((Cliente) selecionado).getTelefone();
        
        Cliente cliente = new Cliente(id, nome, end, tel);
        pedido.setCliente(cliente);
        
        pedido.setValor(calculaValorTotal());
        pedido.setId(idPedido);
        idPedido++;
        
        Date data = new Date();
        pedido.setData(data);
        
        ArrayList<ProdutoPedido> listaPP = new ArrayList();
        copiaListas(listaPP);
        pedido.setProdutospedidos(listaPP);
        
        listaPedidos.add(pedido);
        
        listaProdutoPedido.clear();
        listaOsProdutosAdicionaPedidos2();
        listaOsPedidos();
        jLabelTotal.setText("Total: R$ 0.00"); 
        
        System.out.printf("idPedido: %d\n",idPedido);
        salvaEstado();
    }//GEN-LAST:event_jButtonAdicionaPedidoActionPerformed

    private void jComboBoxAdicionarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdicionarPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAdicionarPedidosActionPerformed

    void retiraPedido(int id){
        Pedido p;
        int n = listaPedidos.size();
        int i;
        for (i=0; i<n; i++) {
            if(listaPedidos.get(i).getId() == id){

                listaPedidos.remove(i);
                
                return;
            }
        }
    } 
    
    private void jButtonRemoverPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPedidoActionPerformed
        
        Object selecionado = jListPedidos.getSelectedValue();
        
        if(selecionado!= null){
            
            int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja remover esse pedido?","Aviso",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                
                int id = ((Pedido) selecionado).getId();       
                retiraPedido(id);  
                listaOsPedidos();
            }            
        }  
    }//GEN-LAST:event_jButtonRemoverPedidoActionPerformed

    void salvaEstado(){
        try {
                FileOutputStream arquivoGrav;
                if(listaPedidos.size() == 0){
                    arquivoGrav = new FileOutputStream("data.dat");
                }else{
                    arquivoGrav = new FileOutputStream("data_"+listaPedidos.get(0).getDateToFile()+".dat");
                }
           
                
                ObjectOutputStream objGrav = new ObjectOutputStream(arquivoGrav);
                objGrav.writeObject(listaClientes);
                objGrav.writeObject(listaPedidos);
                objGrav.writeObject(listaProdutoPedido);
                objGrav.writeObject(listaProdutos);
                objGrav.writeObject(idCliente);
                objGrav.writeObject(idPedido);
                objGrav.writeObject(idProduto);
                objGrav.flush();
                objGrav.close();
                arquivoGrav.flush();
                arquivoGrav.close();
            }
            catch (Exception e2) {
                e2.printStackTrace();
            }
    }
    
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja salvar?","Aviso",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            salvaEstado();
            JOptionPane.showMessageDialog(null, "Seu progresso foi salvo com sucesso.");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja carregar?","Aviso",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            carregaEstado();
        }
    }//GEN-LAST:event_jButtonCarregarActionPerformed

    private void jButtonLimparPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparPedidosActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Deseja excluir todos os pedidos?","Aviso",JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
            listaPedidos.clear();
        }
        listaOsPedidos();
        
    }//GEN-LAST:event_jButtonLimparPedidosActionPerformed

    private void jButtonGerarCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarCsvActionPerformed
        
        if(listaPedidos.size() > 0){
            try{
                float totalvendas = 0;
                String file = listaPedidos.get(0).getDateToFile();
                FileWriter writer = new FileWriter("pedidos_"+file+".csv");

                writer.append("Data,Nome,Valor,Produtos Pedidos");
                writer.append('\n');
                Pedido p;
                int n = listaPedidos.size();
                int i;
                for (i=0; i<n; i++) {
                    p = listaPedidos.get(i);
                    totalvendas+= p.getValor();
                    writer.append(p.getCsvLine());
                    writer.append('\n');
                }

                String stringTotalVendas = Float.toString(totalvendas);
                writer.append('\n');
                writer.append(",Total vendas,"+stringTotalVendas);
                
                writer.flush();
                writer.close();
                JOptionPane.showMessageDialog(null, "Arquivo CSV foi gerado!");
            }
            catch(Exception e){
            } 
        }       
    }//GEN-LAST:event_jButtonGerarCsvActionPerformed

    private void jTextFieldEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoClienteActionPerformed

    private void jButtonEscolheArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscolheArquivoActionPerformed
        
        JFileChooser file = new JFileChooser(); 
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            jLabelNomeArquivo.setText("Nome do arquivo");
        } else {
            File arquivo = file.getSelectedFile();
            jLabelNomeArquivo.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_jButtonEscolheArquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionaPedido;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAdicionarCliente;
    private javax.swing.JButton jButtonAdicionarProduto;
    private javax.swing.JButton jButtonAtualizarCliente;
    private javax.swing.JButton jButtonAtualizarProduto;
    private javax.swing.JButton jButtonCarregar;
    private javax.swing.JButton jButtonEscolheArquivo;
    private javax.swing.JButton jButtonGerarCsv;
    private javax.swing.JButton jButtonLimparPedidos;
    private javax.swing.JButton jButtonRemoverCliente;
    private javax.swing.JButton jButtonRemoverPedido;
    private javax.swing.JButton jButtonRemoverProduto;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxAdicionarPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomeArquivo;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JList jListAdicionaPedidos1;
    private javax.swing.JList jListAdicionaPedidos2;
    private javax.swing.JList jListCliente;
    private javax.swing.JList jListPedidos;
    private javax.swing.JList jListProdutos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldPrecoProduto;
    private javax.swing.JTextField jTextFieldTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
